title: Siyi Huang
# logo: /
description: Data Science Portfolio
  3+ years in data science field
  <br><br>
  Currently working as a Data Analyst at CBRE
  <br><br>
  <a href="https://www.linkedin.com/in/siyi-huang/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
