title: <p align="center"> Siyi Huang </p>

logo: "/images/photo.png?raw=true"

description: 
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/siyi-huang/">LinkedIn</a> |
  <a href="https://github.com/zoe0611">GitHub</a>
  </p>

  <p align="justify">
  First Description
  <br><br>
  Second Description
  <br><br>
  </p>

theme: jekyll-theme-minimal
